### ISSUE TITLE
Improve color conversion accuracy

### ISSUE THREAD

**Issue by crutchcorn** [ceoss/material-colorize#6]
Currently the algorithm we use to convert colors is far from ideal. We should work on making this more accurate (which is highly subjective and we'll need to discuss this further)

**Comment by evelynhathaway** [comment]
This sounds fun so I'll assign myself (as you can assign multiple people)

**Comment by evelynhathaway** [comment]
Here is the table I was working on in that PR's description. Given that the Material palette is fairly small, CIEDE2000 does a great job of finding the nearest color while everything else lags much further behind. "Diff add", the algorithm I made when I was around 14 (haha) and is currently live on the site is funnily enough not much worse than simple euclidian distance or even deltaE94 in some scenarios. I'll be submitting a PR for CIEDE2000 using `color-diff`. I learned a ton from tackling this issue that's been in the back of my mind for years. 😄

---

**Results of closest Material color from edge-case colors**

| Input     | CIEDE2000 | deltaE94  | Euclidian | Diff Add  |
|-----------|-----------|-----------|-----------|-----------|
| `#601936` | `#880E4F` | `#4E342E` | `#4E342E` | `#5D4037` |
| `#244C69` | `#01579B` | `#37474F` | `#37474F` | `#37474F` |
| `#AD6D21` | `#EF6C00` | `#D32F2F` | `#827717` | `#827717` |
| `#5E0000` | `#3E2723` | `#3E2723` | `#3E2723` | `#000000` |
| `#11332C` | `#004D40` | `#263238` | `#263238` | `#263238` |
| `#7D84A4` | `#7986CB` | `#78909C` | `#78909C` | `#78909C` |
| `#9FA263` | `#9E9D24` | `#66BB6A` | `#A1887F` | `#9CCC65` |
| `#5E215D` | `#6A1B9A` | `#880E4F` | `#880E4F` | `#5D4037` |
| `#B76035` | `#D84315` | `#D32F2F` | `#D84315` | `#D32F2F` |

<details> 
<summary>Image and CSS to with/for larger color previews</summary>

![screenshot of table](https://user-images.githubusercontent.com/38994283/54860496-0c07de80-4cd8-11e9-9822-3d6510a5e901.png)

```css
code > span.Box {
	width: 32px !important;
	height: 32px !important;
}
```

</details>

**Comment by crutchcorn** [comment]
This looks AMAZING, wayyy better! Let's get it in! :D
